services:
  - type: web
    name: racknova-backend
    env: python
    rootDir: FASTAPI2
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    plan: free
    envVars:
      - key: DATABASE_URL
        value: "mysql+pymysql://${{MYSQLUSER}}:${{MYSQL_ROOT_PASSWORD}}@${{RAILWAY_TCP_PROXY_DOMAIN}}:${{RAILWAY_TCP_PROXY_PORT}}/${{MYSQL_DATABASE}}"
