services:
  - type: web
    name: racknova-backend
    env: python
    rootDir: FASTAPI2
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    plan: free
    envVars:
      - key: DATABASE_URL
        value: "mysql+pymysql://root:dvDBKWKxwHwlVomUwUaTGVcWzQfKDXHi@mysql.railway.internal:3306/railway"
